name: Dry Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 18
          - 16
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v3
        name: Setup node
        with:
          cache: yarn
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/alorel
      - run: yarn install --immutable
        name: Yarn install
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn run lint
        if: ${{ matrix.node == '18' }}
      - name: Build
        run: yarn run rollup
